steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    args:
      - "build"
      - "--no-cache"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/planlab-ai:$COMMIT_SHA"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_MAPBOX_TOKEN=$_NEXT_PUBLIC_MAPBOX_TOKEN"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push"
    args:
      - "push"
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/planlab-ai:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy"
    entrypoint: "gcloud"
    args:
      - "run"
      - "services"
      - "update"
      - "planlab-ai"
      - "--image"
      - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/planlab-ai:$COMMIT_SHA"
      - "--region"
      - "asia-southeast1"
      - "--platform"
      - "managed"

images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/planlab-ai:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY